# Generated by Django 2.1 on 2019-04-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='ShowImg',
            field=models.FileField(blank=True, null=True, upload_to='./ShowImg'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='UsingImg',
            field=models.FileField(blank=True, null=True, upload_to='./UsewayImg'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='DescribeImg',
            field=models.FileField(blank=True, null=True, upload_to='./DescribeImg'),
        ),
    ]
